default_install_hook_types:
  - pre-commit
  - commit-msg
default_language_version:
  python: "3.13"
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: ["--verbose"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff-check
        args: ["--fix", "--config", "./pyproject.toml"]
      - id: ruff-format
        args: ["--config", "./pyproject.toml"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: ["--toml", "./pyproject.toml"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.17.0"
    hooks:
      - id: mypy
        files: ./
        additional_dependencies:
          [
            "fastapi",
            "loguru",
            "pydantic",
            "pydantic-settings",
          ]
        args: ["--config-file", "./pyproject.toml"]
